import "./globals.css";
import { Inter } from "next/font/google";
import Header from "../layout/Header";
import Footer from "../layout/Footer";
import RecoilRootWrapper from "../providers/RecoilRootWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Refresh Books",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <RecoilRootWrapper>
          <Header />
          <div className={"max-w-[1024px] h-auto m-auto min-h-[70vh]"}>
            {children}
          </div>
          <Footer />
        </RecoilRootWrapper>
      </body>
    </html>
  );
}
